#type: args

train:
  epochs: 100
  batch_size: 32
  lr: 1.0e-3

diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.1
  num_steps: 50
  schedule: "quad"

model:
  is_unconditional: True
  timeemb: 128
  featureemb: 16

